### ISSUE TITLE
技术Tip JVM运行时数据区

### ISSUE THREAD

**Issue by chanjarster** [chanjarster/arts#31]
技术: JVM运行时数据区

参考资料: 

* https://time.geekbang.org/column/article/11289
* https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-2.html#jvms-2.5

研究之后要能够回答以下问题：

1. 这项技术是什么？
1. 这项技术解决了什么问题？
1. 这项技术的工作原理是什么？

研究成果提交形式：

1. 如果有源代码，则commit在本项目中
1. 如果有文章，则应发布在个人博客上，并在评论中给出链接。

**Comment by chanjarster** [comment]
https://chanjarster.github.io/post/jvm/run-time-data-areas/

**Comment by Kuangcp** [comment]
碰巧搜到了，想纠正个错误，常量池在堆里面…不是单独的一个区域，只是一个逻辑区域
